### ISSUE TITLE
Checklist for version update 5.0.0

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#718]
Next version 5.0.0:

- [x] Bump version in CHANGELOG
- [x] Update base layout to include the new version in the HTML
- [x] Update `beautiful-jekyll-theme.gemspec`
- [x] Push to rubygems.org
- [x] Update https://beautifuljekyll.com/updates/
- [x] Update https://beautifuljekyll.com/getstarted/
- [x] Add new Release on github
